POST http://localhost:3000/users/
Content-Type: application/json

{
  "email": "rafael@mks.com",
  "password": "Teste@123",
  "name": "Rafael"
}

###

GET http://localhost:3000/users/a8e0fb63-1799-4a6d-83e0-4f3a8d123cca

###
PATCH http://localhost:3000/users/a8e0fb63-1799-4a6d-83e0-4f3a8d123cca
Content-Type: application/json

{
  "email": "rafael@teste.com",
  "password": "Teste@123",
  "name": "Rafael Fernandes"
}

###
DELETE http://localhost:3000/users/a8e0fb63-1799-4a6d-83e0-4f3a8d123cca

###

POST http://localhost:3000/movies/
Content-Type: application/json

{
  "title": "The Dark Knight",
  "director": "Christopher Nolan",
  "producer": "Warner Bros Entertainment",
  "released": "2008-07-18",
  "genre": "Action"
}

###
GET http://localhost:3000/movies/


###
GET http://localhost:3000/movies/0ee63cd1-67f7-408f-ac05-6220e15b9428

###
PATCH http://localhost:3000/movies/0ee63cd1-67f7-408f-ac05-6220e15b9428
Content-Type: application/json

{
  "title": "The Dark Knight Rises",
  "director": "Christopher Nolan",
  "producer": "Warner Bros Entertainment",
  "released": "2012-07-27",
  "genre": "Action"
}

###
DELETE http://localhost:3000/movies/0ee63cd1-67f7-408f-ac05-6220e15b9428

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "rafael@mks.com",
 "password": "Teste@123"
}
